teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1 # 前後移動
      y: 0 # 左右移動
      z: -1 # 未使用
    axis_angular:
      yaw: 3 # 左右回転
      pitch: -1 # 未使用
      roll: -1 # 未使用

    scale_linear:
      x: 0.7
      y: 0.7
      z: 0.0

    scale_linear_turbo:
      x: 1.0
      y: 1.0
      z: 0.0

    scale_angular:
      yaw: 0.4
      pitch: 0.0
      roll: 0.0

    scale_angular_turbo:
      yaw: 1.0
      pitch: 0.0
      roll: 0.0

    enable_button: 6
    enable_turbo_button: 7
